=== sign-language-translator/sign-language-datasets/schemas/mapping-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "label": {
      "type": "string",
      "minLength": 9,
      "description": "Text label of the sign. Also the filename in the sign dictionary. Format: `country-organization-number_word-sequence(optional-disambiguation)-representing-the-sign`",
      "pattern": "^[a-z]{2}-[a-z]{2,}-[0-9]+_([^ _\\./])+$",
      "examples": ["pk-hfad-1_بادشاہی-مسجد", "pk-hfad-1_bottle(noun)", "pk-fesf-1_able"]
    },
    "components": {
      "type": "array",
      "items": { "$ref": "#/definitions/label" },
      "minItems": 2,
      "description": "List of labels that can be concatenated to form the sign."
    },
    "listOfTexts": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1
    },
    "languages": {
      "type": "object",
      "patternProperties": {
        "^([a-z]{4}-)?[a-z]{2}$": { "$ref": "#/definitions/listOfTexts" }
      },
      "additionalProperties": false,
      "minProperties": 1,
      "description": "Object mapping language code to list of texts of that language. Language code must be ISO 639-1 2-letter language code optionally preceded by optional ISO 15924 4-letter script code and a hyphen. (lower case)",
      "examples": [
        {
          "en": ["hello"]
        },
        {
          "en": ["how are you"],
          "hi": ["आप कैसे हैं"]
        },
        {
          "latn-ur": ["kya haal hai?"],
          "ur": ["کیا حال ہے؟"]
        }
      ]
    }
  },
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "country": {
        "type": "string",
        "description": "ISO 3166-1 alpha-2 country code. (lower case)",
        "pattern": "^[a-z]{2}$"
      },
      "description": {
        "type": "string",
        "description": "The description of this collection. Include Sign Language name, full country name, region name and the full name of the organization."
      },
      "organization": {
        "type": "string",
        "minLength": 2,
        "description": "The short code of the organization which is the source for this dataset. (lower case /[a-z]{2,}/)",
        "pattern": "^[a-z]{2,}$"
      },
      "url": {
        "type": "string",
        "description": "The url where the dataset is hosted or is based on."
      },
      "mapping": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "label": { "$ref": "#/definitions/label" },
            "components": { "$ref": "#/definitions/components" },
            "token": {
              "$ref": "#/definitions/languages",
              "title": "A token is a text word or phrase that represents the sign in the video and has the same meaning."
            },
            "gloss": {
              "$ref": "#/definitions/languages",
              "title": "A gloss is a text with word-for-word mapping of the sign sequence in the video."
            },
            "translation": {
              "$ref": "#/definitions/languages",
              "title": "A translation is a grammatically correct text that has the same meaning as the sign sequence in the video."
            }
          },
          "allOf": [
            { "anyOf": [{ "required": ["label"] }, { "required": ["components"] }] },
            {
              "oneOf": [
                { "required": ["token"] },
                { "anyOf": [{ "required": ["gloss"] }, { "required": ["translation"] }] }
              ]
            }
          ],
          "additionalProperties": false
        },
        "uniqueItems": true
      }
    },
    "required": ["country", "description", "organization", "url", "mapping"]
  }
}

=== sign-language-translator/sign-language-datasets/parallel_texts/pk-sentence-mapping.json
[
  {
    "country": "pk",
    "description": "sentences from pakistan sign language videos taught in hamza foundation academy for the deaf, lahore, pakistan..",
    "mapping": [
      {
        "components": ["pk-hfad-1_aap", "pk-hfad-1_ka", "pk-hfad-1_name", "pk-hfad-1_what", "pk-hfad-1_is"],
        "gloss": {
          "en": ["your name what is"],
          "latn-ur": ["ap ka nam kya hy"],
          "ur": ["آپ کا نام کیا ہے"]
        },
        "label": "pk-hfad-1_aap-ka-nam-kya(what)-hy",
        "translation": {
          "ar": ["ما اسمكَ؟", "ما اسمكِ؟"],
          "de": ["Wie heißen Sie?", "Wie ist ihr Name?"],
          "en": ["What is your name?", "What's your name?", "Your name happens to be what exactly?"],
          "es": ["¿Cómo se llama?", "¿Cuál es su nombre?"],
          "fr": ["quel est votre nom?", "Comment vous appelez-vous?", "Comment tu t'appelles?", "quel est ton nom?"],
          "hi": ["आपका क्या नाम है?"],
          "ja": ["あなたの名前は何ですか？", "お名前は何ですか？", "あなたのお名前は？", "名前は何？"],
          "latn-ar": ["ma ismoka?", "ma ismoki?"],
          "latn-ja": ["Anata no namae wa nanidesuka?", "Onamae wa nandesuka?", "Anata no onamae wa?", "Namae wa nani?"],
          "latn-ru": ["kak vas zovut?"],
          "latn-ur": ["Aap ka naam kya hai?"],
          "latn-zh": ["Qǐngwèn nǐ jiào shénme míngzì?", "Nǐ jiào shénme míngzì?"],
          "ru": ["как вас зовут?"],
          "ur": ["آپ کا نام کیا ہے؟", "آپ کا کیا نام ہے؟", "کیا نام ہے آپکا؟"],
          "zh": ["请问你叫什么名字？", "你叫什么名字？"]
        }
      },
      {
        "gloss": {
          "en": ["god us on mercy amen", "allah us on mercy amen"],
          "latn-ur": ["allah hm pr rehm amen"],
          "ur": ["اللہ ہم پر رحم آمین", "اللہ تعالی ہم پر رحم آمین", "خدا ہم پر رحمت آمین"]
        },
        "label": "pk-hfad-1_allah-hm(us)-pr-rehm-amen",
        "translation": {
          "ar": ["الله يرحمنا، آمين۔"],
          "en": ["God have mercy on us, amen.", "Allah have mercy on us, amen."],
          "latn-ar": ["Allah yarhamna, aamin."],
          "latn-ur": ["Allah ham par reham farma, Aameen."],
          "ur": ["اللہ ہم پر رحم کر، آمین۔", "اللہ تعالی ہم پر رحمت فرما، آمین!", "خدا ہم پر رحم فرما، آمین."]
        }
      },
      {
        "components": ["pk-hfad-1_apna(zati)", "pk-hfad-1_work", "pk-hfad-1_kro"],
        "gloss": {
          "en": ["own work do"],
          "latn-ur": ["apna kam kro"],
          "ur": ["اپنا کام کرو"]
        },
        "label": "pk-hfad-1_apna(zati)-kam-kro",
        "translation": {
          "en": ["Do your work.", "Do your own work."],
          "hi": ["अपना काम करो।"],
          "latn-ur": ["Apna kam kro."],
          "ur": ["اپنا کام کرو۔"]
        }
      },
      {
        "components": ["pk-hfad-1_we", "pk-hfad-1_aaein"],
        "gloss": {
          "en": ["we come"],
          "latn-ur": ["hm aaein"],
          "ur": ["ہم آئیں"]
        },
        "label": "pk-hfad-1_hm(we)-aaein",
        "translation": {
          "en": ["We come"],
          "latn-ur": ["Hum aaein"],
          "ur": ["ہم آئیں"]
        }
      },
      {
        "components": ["pk-hfad-1_we", "pk-hfad-1_jaein", "pk-hfad-1_gy"],
        "gloss": {
          "en": ["we go will"],
          "latn-ur": ["hm jaein ge"],
          "ur": ["ہم جائیں گے"]
        },
        "label": "pk-hfad-1_hm(we)-jaein-gy",
        "translation": {
          "en": ["We will go.", "We'll go."],
          "hi": ["हम जाएंगे।"],
          "latn-ur": ["Hum jaein gy."],
          "ur": ["ہم جائیں گے۔"]
        }
      },
      {
        "gloss": {
          "en": ["our tongue 's knot untie"],
          "latn-ur": ["hmari zuban ki girah khol"],
          "ur": ["ہماری زبان کی گرہ کھول"]
        },
        "label": "pk-hfad-1_hmari-zban-ki-grh-khol",
        "translation": {
          "en": ["Open the knot of our tongue.", "Untie our tongue.", "Open our tongue's knot."],
          "hi": ["हमारी जीभ की गाँठ खोलें।"],
          "latn-ur": ["Humari zuban ki girah kholein."],
          "ur": ["ہماری زبان کی گرہ کھولو۔"]
        }
      },
      {
        "gloss": {
          "en": ["our knowledge in increase amen"],
          "latn-ur": ["hmary ilm mein izafa aameen"],
          "ur": ["ہمارے علم میں اضافہ آمین"]
        },
        "label": "pk-hfad-1_hmary-ilm-mein(in)-azafh-amen",
        "translation": {
          "ar": ["زدنا علمًا آمين"],
          "en": ["Increase our knowledge, Amen."],
          "latn-ar": ["Zdna 'ilman, amin"],
          "latn-ur": ["Hamary ilm me izafa kr, aameen."],
          "ur": ["ہمارے علم میں اضافہ فرما، آمین۔", "ہمارا علم بڑھاو، آمین۔"]
        }
      },
      {
        "components": ["pk-hfad-1_i(me)", "pk-hfad-1_aaun"],
        "gloss": {
          "en": ["i come"],
          "latn-ur": ["main aaun"],
          "ur": ["میں آؤں"]
        },
        "label": "pk-hfad-1_main(i)-aaun",
        "translation": {
          "en": ["I come"],
          "latn-ur": ["Main aaun"],
          "ur": ["میں آؤں"]
        }
      },
      {
        "components": ["pk-hfad-1_tm", "pk-hfad-1_aao"],
        "gloss": {
          "en": ["you come"],
          "latn-ur": ["tum aao"],
          "ur": ["تم آؤ"]
        },
        "label": "pk-hfad-1_tm-aao",
        "translation": {
          "en": ["You come."],
          "hi": ["तुम आओ।"],
          "latn-ur": ["Tum aao."],
          "ur": ["تم آؤ۔"]
        }
      },
      {
        "components": ["pk-hfad-1_that", "pk-hfad-1_aaei(came)"],
        "gloss": {
          "en": ["she came"],
          "latn-ur": ["wo aai"],
          "ur": ["وہ آئی"]
        },
        "label": "pk-hfad-1_wo-aaei(came)",
        "translation": {
          "de": ["sie kam."],
          "en": ["She came."],
          "es": ["Ella vino."],
          "fr": ["Elle est venue."],
          "hi": ["वह आयी."],
          "latn-ru": ["Ona prishla."],
          "latn-ur": ["Wo aai."],
          "ru": ["Она пришла."],
          "ur": ["وہ آئی۔"]
        }
      },
      {
        "components": ["pk-hfad-1_that", "pk-hfad-1_aaey"],
        "gloss": {
          "en": ["they came"],
          "latn-ur": ["wo aaey"],
          "ur": ["وہ آئے"]
        },
        "label": "pk-hfad-1_wo-aaey",
        "translation": {
          "ar": ["لقد جاؤوا."],
          "de": ["sie kamen."],
          "en": ["They came."],
          "es": ["Ellos vinieron.", "Ellas vinieron."],
          "fr": ["Ils sont venus."],
          "hi": ["वे आए।"],
          "latn-ar": ["laqad ja'u."],
          "latn-ru": ["Oni prishli."],
          "latn-ur": ["Wo aaey."],
          "ru": ["Они пришли."],
          "ur": ["وہ آئے۔"]
        }
      },
      {
        "components": ["pk-hfad-1_that", "pk-hfad-1_aaia(came)"],
        "gloss": {
          "en": ["he came", "he arrived"],
          "latn-ur": ["wo aaya"],
          "ur": ["وہ آیا"]
        },
        "label": "pk-hfad-1_wo-aaia(came)",
        "translation": {
          "en": ["He came.", "He arrived."],
          "hi": ["वो आया.", "वह आया।"],
          "latn-ur": ["Wo aaya."],
          "ur": ["وہ آیا۔"]
        }
      },
      {
        "components": ["pk-hfad-1_that", "pk-hfad-1_gia", "pk-hfad-1_tha"],
        "gloss": {
          "latn-ur": ["wo gya tha"],
          "ur": ["وہ گیا تھا"]
        },
        "label": "pk-hfad-1_wo-gia-tha",
        "translation": {
          "en": ["He went."],
          "hi": ["वह गया था।"],
          "latn-ur": ["Wo gya tha."],
          "ur": ["وہ گیا تھا۔"]
        }
      }
    ],
    "organization": "hfad",
    "url": "https://www.youtube.com/@pslhamzafoundationacademyf7624/videos"
  }
]
